'use client';
import {useRef,useState} from 'react';
const P=[['#111111','#D8FF36','#F5F4EE','#777777','#FFFFFF','#D7D7D0'],['#12263A','#4EA5D9','#F4F1EA','#C9D6DF','#FFFFFF','#315B7D'],['#332C2F','#E7C8A0','#F7F2EA','#A5A58D','#FFFFFF','#6B705C']];
const fonts=['Arial','Aptos','Calibri','Georgia','Times New Roman','Trebuchet MS','Verdana'];
export default function Page(){const [open,setOpen]=useState(false),[step,setStep]=useState(1),[company,setCompany]=useState('Your Company'),[logo,setLogo]=useState('/tmpl_black.svg'),[colors,setColors]=useState(P[0]),[hf,setHf]=useState('Arial'),[bf,setBf]=useState('Arial');const file=useRef();
const upload=e=>{let f=e.target.files?.[0];if(f)setLogo(URL.createObjectURL(f))};const color=(i,v)=>{let n=[...colors];n[i]=v.toUpperCase();setColors(n)};
return <main><header><div className="shell nav"><img src="/tmpl_black.svg"/><nav><a href="#how">How it works</a><a href="#layouts">Layouts</a><a href="#included">What's included</a><button onClick={()=>setOpen(true)}>Create your TMPL →</button></nav></div></header>
<section className="shell hero"><div><small>POWERPOINT, BUILT FOR YOUR BRAND</small><h1>Your brand.<br/>Your TMPL.</h1></div><div className="heror"><p>One professional PowerPoint system. 30 essential layouts, customized with your logo, colors and fonts.</p><div><button onClick={()=>setOpen(true)}>Create your TMPL →</button><b>$99</b><span>one-time</span></div></div></section>
<section className="shell demo"><div className="chrome"><div><i/> TMPL Builder</div><span>Brand setup&nbsp;&nbsp;1 / 4</span></div><div className="demobody"><aside><small>YOUR TMPL</small><b>01&nbsp; Brand</b><span>02&nbsp; Colors</span><span>03&nbsp; Typography</span><span>04&nbsp; Preview</span></aside><div className="work"><div className="worktop"><b>Build your brand setup</b><em>Saved automatically</em></div><div className="cards"><div className="card"><label>COMPANY LOGO</label><div className="drop"><img src="/tmpl_black.svg"/><span>Drop your logo here</span></div></div><div className="card"><label>BRAND COLORS</label><div className="swatches">{colors.slice(0,4).map(c=><i key={c} style={{background:c}}/>)}</div><label>TYPOGRAPHY</label><div className="field">Heading — Arial Bold</div><div className="field">Body — Arial Regular</div></div></div><Preview logo="/tmpl_black.svg" company="TMPL" colors={colors}/></div></div></section>
<div className="shell proof"><span>✓ 30 professional layouts</span><span>✓ Your colors & fonts</span><span>✓ Fully editable PowerPoint</span><span>✓ No subscription</span></div>
<section id="how" className="shell section"><div className="head"><h2>Three steps.<br/>One finished TMPL.</h2><p>No briefing calls and no design project. Add the essentials of your brand and TMPL turns them into a clean, ready-to-use PowerPoint template.</p></div><div className="steps">{[['01 — UPLOAD','Add your logo.','Upload your company logo and basic brand information.'],['02 — CUSTOMIZE','Set colors & fonts.','Add up to six brand colors and choose your typography.'],['03 — DOWNLOAD','Get your TMPL.','Your branded PowerPoint template is generated and ready to use.']].map(x=><article key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section id="layouts" className="shell section"><div className="head"><h2>30 layouts.<br/>Built to work.</h2><p>A compact presentation system for the slides companies actually need. No decorative filler and no endless layout hunting.</p></div><div className="layouts">{['Cover','Section opener','Big statement','Text + image','Key figures','Process','Team','Closing slide'].map((x,i)=><div key={x}><small>{String(i+1).padStart(2,'0')} / {x.toUpperCase()}</small><h4>{x}</h4><i/></div>)}</div></section>
<section id="included" className="shell section included"><h2>Everything you need.<br/>Nothing you don't.</h2><div>{['30 professional layouts','Your logo','1–6 brand colors','Brand typography','PowerPoint theme','Charts & tables','Image layouts','Fully editable'].map(x=><span key={x}>✓ {x}</span>)}</div></section>
<section className="closing"><div className="shell"><h2>Build your PowerPoint around your brand.</h2><div><p>30 professional layouts. Your logo, colors and fonts. $99 once.</p><button className="lime" onClick={()=>setOpen(true)}>Create your TMPL →</button></div></div></section><footer><div className="shell"><img src="/tmpl_black.svg"/><span>Your brand. Your TMPL.</span><span>Terms · Privacy · Contact</span></div></footer>
{open&&<div className="overlay"><div className="builder"><div className="btop"><img src="/tmpl_black.svg"/><b>TMPL Builder <span>{step} / 4</span></b><button onClick={()=>setOpen(false)}>×</button></div><div className="bbody"><aside>{['Brand','Colors','Typography','Preview'].map((x,i)=><button className={step===i+1?'active':''} onClick={()=>setStep(i+1)} key={x}><small>0{i+1}</small>{x}</button>)}</aside><div className="form">
{step===1&&<><small>01 / BRAND</small><h2>Start with your brand.</h2><p>Add your company name and logo. You can change these before checkout.</p><label>Company name</label><input value={company} onChange={e=>setCompany(e.target.value)}/><label>Company logo</label><div className="upload" onClick={()=>file.current.click()}><img src={logo}/><b>Upload logo</b><span>SVG, PNG or JPG</span></div><input ref={file} hidden type="file" accept=".svg,.png,.jpg,.jpeg" onChange={upload}/></>}
{step===2&&<><small>02 / COLORS</small><h2>Set your colors.</h2><p>Add up to six brand colors or start with one of our palettes.</p><div className="colorinputs">{colors.map((c,i)=><div key={i}><input type="color" value={c} onChange={e=>color(i,e.target.value)}/><input value={c} onChange={e=>color(i,e.target.value)}/></div>)}</div><label>Ready-made palettes</label><div className="palettes">{P.map((p,i)=><button onClick={()=>setColors(p)} key={i}>{p.map(c=><i style={{background:c}} key={c}/>)}</button>)}</div></>}
{step===3&&<><small>03 / TYPOGRAPHY</small><h2>Choose your type.</h2><p>Start with dependable PowerPoint-safe font choices.</p><label>Heading font</label><select value={hf} onChange={e=>setHf(e.target.value)}>{fonts.map(x=><option key={x}>{x}</option>)}</select><label>Body font</label><select value={bf} onChange={e=>setBf(e.target.value)}>{fonts.map(x=><option key={x}>{x}</option>)}</select></>}
{step===4&&<><small>04 / PREVIEW</small><h2>This is your TMPL.</h2><p>Preview your brand setup before checkout.</p><Preview logo={logo} company={company} colors={colors} hf={hf} bf={bf}/><div className="summary"><div><small>POWERPOINT TEMPLATE</small><b>30 layouts · Fully editable</b></div><strong>$99</strong></div><button className="checkout" onClick={()=>alert('Next integration: Stripe → PowerPoint generation → download.')}>Continue to checkout →</button></>}
</div><div className="live"><small>LIVE PREVIEW</small><Preview logo={logo} company={company} colors={colors} hf={hf} bf={bf}/></div></div><div className="bbot"><span>No account required. Pay once and download your TMPL.</span><div><button className="back" disabled={step===1} onClick={()=>setStep(step-1)}>← Back</button>{step<4&&<button onClick={()=>setStep(step+1)}>Continue →</button>}</div></div></div></div>}</main>}
function Preview({logo,company,primary,accent,heading,body}){
 const hf = webFont[heading] || 'Arial, Helvetica, sans-serif';
 const bf = webFont[body] || 'Arial, Helvetica, sans-serif';
 const slides = [
   {bg:'#ffffff', fg:'#111111', bar:primary, title:'Designed around your brand.'},
   {bg:accent, fg:'#111111', bar:primary, title:'One clear message.'},
   {bg:primary, fg:'#ffffff', bar:accent, title:'Numbers that stand out.'}
 ];
 return <div className="previewStrip">
   {slides.map((sl,i)=>
     <div className="pv" key={i} style={{background:sl.bg,color:sl.fg,fontFamily:bf}}>
       <div className="pvLogo"><img src={logo} alt="Company logo"/></div>
       <h5 style={{fontFamily:hf}}>{sl.title}</h5>
       <small>{company}</small>
       <i style={{background:sl.bar}}/>
     </div>
   )}
 </div>
}
